### ISSUE TITLE
having a screenshot with a little description in readme would be great

### ISSUE THREAD

**Issue by touseefbsb** [colinkiama/FluentPivotApp#1]
you seem to make good uwp controls, having a screenshot in readme can help the developers get an idea of wht the control or project is about, right now I have to clone the project and run it in order to see the visual results or functionality of the control , which is time consuming :)

**Comment by colinkiama** [comment]
Sorry about that, I usually take my time when updating readme's on GitHub. I'll keep that in mind next time.

**Comment by touseefbsb** [comment]
yeah sure you can update the readme in 2nd or 3rd commit, but in the first commit u can just provide 1 or 2 line description and at the end just write : "readme will be updated soon with more info"

**Comment by colinkiama** [comment]
Okay, will do in future
